reject:
  # ILP-Packet <= v2.2.0 is required to support the ILP-Packet version 1 used by the Mojaloop Specification v1.x.
  - "ilp-packet-v1"
  # eslint-config-airbnb-base relies on eslint < 9.0.0
  - "eslint"
  # axios v1.13.3 introduces some error object changes that break request-errors.test.js. Needs investigation.
  - "axios"
